/* ============================================
   INSTALLMENTS.JS — compras en cuotas
   Comparte el mismo patrón de auto-generación mensual + confirmación
   manual de pago ya resuelto para gastos fijos (js/recurring.js), pero
   es una entidad finita en el tiempo (cantidad de cuotas conocida de
   antemano), no indefinida como un gasto fijo.
   ============================================ */

/* ---------- Helpers de fecha ---------- */

/* Suma `monthsToAdd` meses a `dateISO`, clampeando el día al último día
   disponible del mes destino (mismo criterio ya usado en recurring.js
   para dayOfMonth, ej. 31 de enero + 1 mes = 28/29 de febrero). */
function addMonthsClamped(dateISO, monthsToAdd) {
  const d = dateFromISO(dateISO);
  const day = d.getDate();
  const targetYear = d.getFullYear();
  const targetMonth = d.getMonth() + monthsToAdd;
  const daysInTargetMonth = new Date(targetYear, targetMonth + 1, 0).getDate();
  const clampedDay = Math.min(day, daysInTargetMonth);
  return new Date(targetYear, targetMonth, clampedDay);
}

function installmentStats(p) {
  const paidCount = p.payments.filter(pm => pm.paid).length;
  const remaining = Math.max(0, p.totalInstallments - paidCount);
  const complete = paidCount >= p.totalInstallments;
  const pendingBalance = p.cancelled ? 0 : remaining * p.installmentAmount;
  const endDate = addMonthsClamped(p.startDate, p.totalInstallments - 1);
  return { paidCount, remaining, complete, pendingBalance, endDate };
}

/* ---------- Auto-generation ---------- */

/* Genera, para el mes en curso, la cuota pendiente de cada compra en
   cuotas activa que todavía no llegó a su total. Igual que los gastos
   fijos: se genera con pending:true sin importar el día, y el usuario
   confirma el pago a mano — nunca se auto-marca como pagada por el
   solo paso de la fecha. */
function processInstallmentPurchases() {
  if (!state.installmentPurchases || state.installmentPurchases.length === 0) return [];
  const now = new Date();
  const monthKey = yearMonthKey(now);
  const generated = [];

  state.installmentPurchases.forEach(p => {
    if (p.cancelled) return;

    const paidCount = p.payments.filter(pm => pm.paid).length;
    if (paidCount >= p.totalInstallments) return; // ya completa

    const startMonthKey = p.startDate.slice(0, 7);
    if (monthKey < startMonthKey) return; // todavía no llegó el mes de la primera cuota

    const alreadyThisMonth = state.entries.some(
      e => e.installmentPurchaseId === p.id && e.date.startsWith(monthKey)
    );
    if (alreadyThisMonth) return;

    const nextNumber = paidCount + 1;
    if (nextNumber > p.totalInstallments) return;

    const startDay = dateFromISO(p.startDate).getDate();
    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    const day = Math.min(startDay, daysInMonth);
    const dateISO = `${monthKey}-${String(day).padStart(2, '0')}`;

    p.payments.push({ id: uid(), installmentNumber: nextNumber, date: dateISO, paid: false });

    state.entries.push({
      id: uid(),
      type: 'expense',
      amount: p.installmentAmount,
      categoryId: p.categoryId || 'cuotas',
      accountId: p.accountId,
      note: `${p.name} · cuota ${nextNumber}/${p.totalInstallments}`,
      date: dateISO,
      createdAt: Date.now(),
      installmentPurchaseId: p.id,
      installmentNumber: nextNumber,
      autoGenerated: true,
      pending: true,
    });
    generated.push(p.name);
  });

  return generated;
}

/* Se llama en cada apertura de la app. Toast separado del de gastos/
   ingresos fijos (evita mezclar dominios distintos en un solo mensaje),
   con un delay mayor para no clobbear el toast de recurring si ambos
   generaron algo en la misma apertura. */
function processInstallmentPurchasesWithToast() {
  const generated = processInstallmentPurchases();
  if (generated.length > 0) {
    saveState();
    renderAll();
    renderInstallmentManager();
    const now = new Date();
    const monthName = MONTH_NAMES[now.getMonth()];
    const msg = generated.length === 1
      ? `Cuota de "${generated[0]}" generada para ${monthName}`
      : `${generated.length} cuotas generadas para ${monthName}`;
    setTimeout(() => showToast(msg), 2500);
  }
}

/* Confirmación manual de pago de una cuota puntual. Reusa
   confirmPendingPayment() de recurring.js para el estado del entry
   (pending:false + paidAt), y además actualiza el registro de la cuota
   dentro de la compra en cuotas. */
function confirmInstallmentPayment(entryId) {
  const entry = state.entries.find(e => e.id === entryId);
  if (!entry || !entry.installmentPurchaseId) return;
  const purchase = state.installmentPurchases.find(p => p.id === entry.installmentPurchaseId);

  entry.pending = false;
  entry.paidAt = Date.now();

  let justCompleted = false;
  if (purchase) {
    const payment = purchase.payments.find(pm => pm.installmentNumber === entry.installmentNumber);
    if (payment) payment.paid = true;
    const paidCount = purchase.payments.filter(pm => pm.paid).length;
    justCompleted = paidCount >= purchase.totalInstallments;
  }

  saveState();
  renderAll();
  renderInstallmentManager();
  showToast(justCompleted && purchase ? `"${purchase.name}" pagada por completo 🎉` : 'Cuota pagada');
}

/* ---------- Manager / list rendering (Ajustes) ---------- */

function renderInstallmentManager() {
  const container = document.getElementById('installment-manager');
  const summaryEl = document.getElementById('installment-summary');
  if (!container) return;
  const list = state.installmentPurchases || [];
  container.innerHTML = '';

  if (list.length === 0) {
    container.innerHTML = `<p class="recurring-empty">todavía no hay compras en cuotas</p>`;
    if (summaryEl) summaryEl.innerHTML = '';
    return;
  }

  const monthKey = yearMonthKey(new Date());
  let committedThisMonth = 0;
  let totalPending = 0;

  list.forEach(p => {
    const { paidCount, complete, pendingBalance, endDate } = installmentStats(p);
    totalPending += pendingBalance;

    const thisMonthPayment = p.payments.find(pm => pm.date.startsWith(monthKey));
    if (thisMonthPayment) committedThisMonth += p.installmentAmount;

    const cat = p.categoryId ? getCategoryById(p.categoryId, 'expense') : null;
    const icon = cat ? cat.icon : '🧾';

    let statusLine;
    if (p.cancelled) {
      statusLine = `cancelada · ${paidCount} de ${p.totalInstallments} cuotas pagadas`;
    } else if (complete) {
      statusLine = 'pagada por completo ✓';
    } else {
      statusLine = `saldo pendiente: ${formatMoney(pendingBalance)} · fin estimado: ${formatShortDate(endDate)}`;
    }
    const progressLabel = complete
      ? `${p.totalInstallments} de ${p.totalInstallments}`
      : `cuota ${paidCount + 1} de ${p.totalInstallments}`;
    const progressPct = Math.min(100, Math.round((paidCount / p.totalInstallments) * 100));

    const row = document.createElement('div');
    row.className = 'recurring-row';
    row.innerHTML = `
      <div class="recurring-row-info">
        <span class="recurring-row-name">${icon} ${escapeHtml(p.name)}</span>
        <span class="recurring-row-detail">${progressLabel} · ${formatMoney(p.installmentAmount)}/cuota</span>
        <div class="installment-progress-track"><div class="installment-progress-fill" style="width:${progressPct}%"></div></div>
        <span class="recurring-row-detail">${statusLine}</span>
      </div>
      <div class="recurring-row-actions">
        <button class="cat-edit inst-edit" data-inst-id="${p.id}">editar</button>
        <button class="cat-remove inst-remove" data-inst-id="${p.id}">quitar</button>
      </div>
    `;
    container.appendChild(row);
  });

  if (summaryEl) {
    summaryEl.innerHTML = `
      <p class="installment-summary-line">tenés <strong>${formatMoney(committedThisMonth)}</strong> comprometidos en cuotas este mes</p>
      <p class="installment-summary-line">${formatMoney(totalPending)} en total pendiente</p>
    `;
  }

  container.querySelectorAll('.inst-edit').forEach(btn => {
    btn.addEventListener('click', () => {
      const p = state.installmentPurchases.find(x => x.id === btn.dataset.instId);
      if (p) openEditInstallmentModal(p);
    });
  });
  container.querySelectorAll('.inst-remove').forEach(btn => {
    btn.addEventListener('click', () => removeInstallmentPurchase(btn.dataset.instId));
  });
}

function formatShortDate(d) {
  return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`;
}

function removeInstallmentPurchase(id) {
  const p = state.installmentPurchases.find(x => x.id === id);
  if (!p) return;
  const paidCount = p.payments.filter(pm => pm.paid).length;

  if (paidCount > 0) {
    if (confirm(`"${p.name}" ya tiene cuotas pagadas. ¿Querés cancelarla en vez de eliminarla?\n\nCancelar: deja de generar cuotas nuevas, conserva el historial de lo ya pagado.\nEliminar: borra la definición completa (los movimientos ya generados quedan en el historial de movimientos).`)) {
      p.cancelled = true;
    } else {
      if (!confirm('¿Confirmar eliminación definitiva de la compra en cuotas?')) return;
      state.installmentPurchases = state.installmentPurchases.filter(x => x.id !== id);
    }
  } else {
    if (!confirm(`¿Eliminar "${p.name}"?`)) return;
    state.installmentPurchases = state.installmentPurchases.filter(x => x.id !== id);
  }
  saveState();
  renderInstallmentManager();
}

/* ---------- Modal open/close ---------- */

function openInstallmentModal() {
  editingInstallmentId = null;
  _openInstallmentModalShared('nueva compra en cuotas', 'guardar compra en cuotas');
}

function openEditInstallmentModal(p) {
  editingInstallmentId = p.id;
  _openInstallmentModalShared('editar compra en cuotas', 'guardar cambios', p);
}

function _openInstallmentModalShared(title, saveLabel, p) {
  closeAllModals();
  document.getElementById('installment-modal-title').textContent = title;
  document.getElementById('btn-save-installment').textContent = saveLabel;
  document.getElementById('installment-name').value = p ? p.name : '';
  document.getElementById('installment-amount').value = p ? p.installmentAmount : '';
  document.getElementById('installment-count').value = p ? p.totalInstallments : '';
  document.getElementById('installment-start-date').value = p ? p.startDate : todayISO();
  selectedCategoryIdForInstallment = p ? (p.categoryId || null) : null;
  selectedAccountIdForInstallment = p
    ? p.accountId
    : (state.accounts.length > 0 ? state.accounts[0].id : null);
  setInstallmentAmountMode('per-installment');
  renderInstallmentCategoryGrid();
  renderInstallmentAccountGrid();
  document.getElementById('installment-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeInstallmentModal() {
  editingInstallmentId = null;
  document.getElementById('installment-modal-backdrop').hidden = true;
}

/* ---------- Amount mode toggle: por cuota | monto total ---------- */

function setInstallmentAmountMode(mode) {
  installmentAmountMode = mode;
  document.querySelectorAll('#installment-amount-mode-selector .account-type-btn').forEach(btn => {
    btn.classList.toggle('selected', btn.dataset.mode === mode);
  });
  const label = document.getElementById('installment-amount-label');
  const input = document.getElementById('installment-amount');
  if (mode === 'total') {
    label.textContent = 'monto total de la compra';
    input.placeholder = 'ej: 120000';
  } else {
    label.textContent = 'monto por cuota';
    input.placeholder = 'ej: 10000';
  }
  updateInstallmentAmountPreview();
}

function updateInstallmentAmountPreview() {
  const preview = document.getElementById('installment-per-unit-preview');
  if (!preview) return;
  const amountRaw = parseFloat(document.getElementById('installment-amount').value);
  const count = parseInt(document.getElementById('installment-count').value, 10);
  if (installmentAmountMode === 'total' && amountRaw > 0 && count > 0) {
    preview.textContent = `≈ ${formatMoney(amountRaw / count)} por cuota`;
    preview.hidden = false;
  } else {
    preview.hidden = true;
  }
}

/* ---------- Category & account grids ---------- */

function renderInstallmentCategoryGrid() {
  const grid = document.getElementById('installment-category-grid');
  if (!grid) return;
  grid.innerHTML = '';

  const noneChip = document.createElement('button');
  noneChip.type = 'button';
  noneChip.className = 'category-chip' + (!selectedCategoryIdForInstallment ? ' selected' : '');
  noneChip.innerHTML = `<span style="color:var(--ink-faint);padding:0 4px">sin categoría</span>`;
  noneChip.addEventListener('click', () => {
    selectedCategoryIdForInstallment = null;
    renderInstallmentCategoryGrid();
  });
  grid.appendChild(noneChip);

  state.categories.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryIdForInstallment === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryIdForInstallment = cat.id;
      renderInstallmentCategoryGrid();
    });
    grid.appendChild(chip);
  });
}

function renderInstallmentAccountGrid() {
  const grid = document.getElementById('installment-account-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.accounts.forEach(acc => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedAccountIdForInstallment === acc.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${acc.icon}</span><span>${escapeHtml(acc.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedAccountIdForInstallment = acc.id;
      renderInstallmentAccountGrid();
    });
    grid.appendChild(chip);
  });
}

/* ---------- Save ---------- */

function saveInstallmentPurchase() {
  const name = document.getElementById('installment-name').value.trim();
  const amountRaw = parseFloat(document.getElementById('installment-amount').value);
  const count = parseInt(document.getElementById('installment-count').value, 10);
  const startDate = document.getElementById('installment-start-date').value;

  if (!name) { showToast('Ponele un nombre a la compra'); return; }
  if (!count || count < 1) { showToast('La cantidad de cuotas debe ser al menos 1'); return; }
  if (!amountRaw || amountRaw <= 0) { showToast('Ingresá un monto válido'); return; }
  if (!startDate) { showToast('Elegí la fecha de la primera cuota'); return; }
  if (!selectedAccountIdForInstallment) { showToast('Elegí una cuenta'); return; }

  const installmentAmount = installmentAmountMode === 'total' ? amountRaw / count : amountRaw;

  if (editingInstallmentId) {
    const p = state.installmentPurchases.find(x => x.id === editingInstallmentId);
    if (p) {
      const paidCount = p.payments.filter(pm => pm.paid).length;
      if (count < paidCount) {
        showToast(`No podés poner menos cuotas que las ya pagadas (${paidCount})`);
        return;
      }
      // Las cuotas ya pagadas no se recalculan retroactivamente: sus
      // entries y registros en `payments` quedan con el monto vigente al
      // momento en que se generaron. Solo cambia lo que se usa para
      // generar las cuotas futuras.
      p.name = name;
      p.installmentAmount = installmentAmount;
      p.totalInstallments = count;
      p.startDate = startDate;
      p.accountId = selectedAccountIdForInstallment;
      p.categoryId = selectedCategoryIdForInstallment || null;
    }
    saveState();
    closeInstallmentModal();
    renderInstallmentManager();
    showToast('Compra en cuotas actualizada');
    return;
  }

  state.installmentPurchases.push({
    id: uid(),
    name,
    totalInstallments: count,
    installmentAmount,
    startDate,
    accountId: selectedAccountIdForInstallment,
    categoryId: selectedCategoryIdForInstallment || null,
    payments: [],
  });
  // Genera la cuota 1 al toque (no esperar al próximo init() de la app)
  // para que el usuario la vea aparecer de inmediato.
  processInstallmentPurchases();
  saveState();
  closeInstallmentModal();
  renderInstallmentManager();
  renderAll();
  showToast('Compra en cuotas agregada');
}
