/* ============================================
   RECURRING.JS — gastos fijos / recurrentes
   ============================================ */

function processRecurringExpenses() {
  if (!state.recurringExpenses || state.recurringExpenses.length === 0) return;

  const now = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const generated = [];

  state.recurringExpenses.forEach(rec => {
    if (!rec.active) return;
    const alreadyExists = state.entries.some(
      e => e.recurringId === rec.id && e.date.startsWith(monthKey)
    );
    if (alreadyExists) return;

    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    const day = Math.min(rec.dayOfMonth, daysInMonth);
    const dateISO = `${monthKey}-${String(day).padStart(2, '0')}`;

    state.entries.push({
      id: uid(),
      type: 'expense',
      amount: rec.amount,
      categoryId: rec.categoryId,
      accountId: rec.accountId,
      note: rec.name,
      date: dateISO,
      createdAt: Date.now(),
      recurringId: rec.id,
      autoGenerated: true,
    });
    generated.push(rec.name);
  });

  if (generated.length > 0) {
    saveState();
    renderAll();
    const monthName = MONTH_NAMES[now.getMonth()];
    const msg = generated.length === 1
      ? `Gasto fijo "${generated[0]}" generado para ${monthName}`
      : `${generated.length} gastos fijos generados para ${monthName}`;
    setTimeout(() => showToast(msg), 150);
  }
}

function renderRecurringManager() {
  const container = document.getElementById('recurring-manager');
  if (!container) return;
  container.innerHTML = '';

  if (state.recurringExpenses.length === 0) {
    container.innerHTML = '<p class="recurring-empty">todavía no hay gastos fijos</p>';
    return;
  }

  state.recurringExpenses.forEach(rec => {
    const cat = getCategoryById(rec.categoryId, 'expense');
    const row = document.createElement('div');
    row.className = 'recurring-row';
    row.innerHTML = `
      <div class="recurring-row-info">
        <span class="recurring-row-name">${cat.icon} ${escapeHtml(rec.name)}</span>
        <span class="recurring-row-detail">${formatMoney(rec.amount)} · día ${rec.dayOfMonth}</span>
      </div>
      <div class="recurring-row-actions">
        <button class="recurring-toggle${rec.active ? ' active' : ''}" data-rec-id="${rec.id}">
          ${rec.active ? 'pausar' : 'activar'}
        </button>
        <button class="cat-remove" data-rec-id="${rec.id}">quitar</button>
      </div>
    `;
    container.appendChild(row);
  });

  container.querySelectorAll('.recurring-toggle').forEach(btn => {
    btn.addEventListener('click', () => {
      const rec = state.recurringExpenses.find(r => r.id === btn.dataset.recId);
      if (!rec) return;
      rec.active = !rec.active;
      saveState();
      renderRecurringManager();
    });
  });

  container.querySelectorAll('.cat-remove[data-rec-id]').forEach(btn => {
    btn.addEventListener('click', () => {
      state.recurringExpenses = state.recurringExpenses.filter(r => r.id !== btn.dataset.recId);
      saveState();
      renderRecurringManager();
    });
  });
}

function openRecurringModal() {
  closeAllModals();
  document.getElementById('recurring-name').value = '';
  document.getElementById('recurring-amount').value = '';
  document.getElementById('recurring-day').value = '';
  selectedCategoryIdForRecurring = null;
  selectedAccountIdForRecurring = state.accounts.length > 0 ? state.accounts[0].id : null;
  renderRecurringCategoryGrid();
  renderRecurringAccountGrid();
  document.getElementById('recurring-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeRecurringModal() {
  document.getElementById('recurring-modal-backdrop').hidden = true;
}

function openAccountFromRecurring() {
  pendingRecurringData = {
    name: document.getElementById('recurring-name').value,
    amount: document.getElementById('recurring-amount').value,
    day: document.getElementById('recurring-day').value,
    categoryId: selectedCategoryIdForRecurring,
  };
  editingAccountId = null;
  closeAllOverlaysAndModals();
  document.getElementById('account-modal-title').textContent = 'nueva cuenta';
  document.getElementById('new-account-name').value = '';
  document.getElementById('new-account-initial-balance').value = '';
  document.getElementById('account-adjustment-section').hidden = true;
  document.getElementById('btn-save-account').textContent = 'agregar cuenta';
  selectedIconForNewAccount = ACCOUNT_ICON_OPTIONS[0];
  selectedAccountType = 'cash';
  renderAccountIconPicker();
  updateAccountTypeSelector();
  document.getElementById('account-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function restoreRecurringModal(data) {
  document.getElementById('recurring-name').value = data.name || '';
  document.getElementById('recurring-amount').value = data.amount || '';
  document.getElementById('recurring-day').value = data.day || '';
  selectedCategoryIdForRecurring = data.categoryId || null;
  renderRecurringCategoryGrid();
  renderRecurringAccountGrid();
  document.getElementById('recurring-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function renderRecurringCategoryGrid() {
  const grid = document.getElementById('recurring-category-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.categories.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryIdForRecurring === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryIdForRecurring = cat.id;
      renderRecurringCategoryGrid();
    });
    grid.appendChild(chip);
  });
}

function renderRecurringAccountGrid() {
  const grid = document.getElementById('recurring-account-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.accounts.forEach(acc => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedAccountIdForRecurring === acc.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${acc.icon}</span><span>${escapeHtml(acc.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedAccountIdForRecurring = acc.id;
      renderRecurringAccountGrid();
    });
    grid.appendChild(chip);
  });
  const addChip = document.createElement('button');
  addChip.type = 'button';
  addChip.className = 'category-chip add-new-chip';
  addChip.innerHTML = `<span class="chip-icon">＋</span><span>nueva cuenta</span>`;
  addChip.addEventListener('click', openAccountFromRecurring);
  grid.appendChild(addChip);
}

function saveRecurring() {
  const name = document.getElementById('recurring-name').value.trim();
  const amount = parseFloat(document.getElementById('recurring-amount').value);
  const day = parseInt(document.getElementById('recurring-day').value, 10);

  if (!name) { showToast('Ponele un nombre al gasto fijo'); return; }
  if (!amount || amount <= 0) { showToast('Ingresá un monto válido'); return; }
  if (!day || day < 1 || day > 28) { showToast('El día debe estar entre 1 y 28'); return; }
  if (!selectedCategoryIdForRecurring) { showToast('Elegí una categoría'); return; }
  if (!selectedAccountIdForRecurring) { showToast('Elegí una cuenta'); return; }

  state.recurringExpenses.push({
    id: uid(),
    name,
    amount,
    categoryId: selectedCategoryIdForRecurring,
    accountId: selectedAccountIdForRecurring,
    dayOfMonth: day,
    active: true,
  });

  saveState();
  closeRecurringModal();
  renderRecurringManager();
  showToast('Gasto fijo agregado');
}
