/* ============================================
   RECURRING.JS — gastos e ingresos fijos / recurrentes
   ============================================ */

/* ---------- Auto-generation ---------- */

function processRecurring(list, entryType) {
  if (!list || list.length === 0) return [];
  const now = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const generated = [];

  list.forEach(rec => {
    if (!rec.active) return;
    const alreadyExists = state.entries.some(
      e => e.recurringId === rec.id && e.date.startsWith(monthKey)
    );
    if (alreadyExists) return;

    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    const day = Math.min(rec.dayOfMonth, daysInMonth);
    const dateISO = `${monthKey}-${String(day).padStart(2, '0')}`;

    state.entries.push({
      id: uid(),
      type: entryType,
      amount: rec.amount,
      categoryId: rec.categoryId,
      accountId: rec.accountId,
      note: rec.name,
      date: dateISO,
      createdAt: Date.now(),
      recurringId: rec.id,
      autoGenerated: true,
    });
    generated.push(rec.name);
  });

  return generated;
}

function processRecurringExpenses() {
  const generatedExp = processRecurring(state.recurringExpenses, 'expense');
  const generatedInc = processRecurring(state.recurringIncomes, 'income');
  const all = [...generatedExp, ...generatedInc];

  if (all.length > 0) {
    saveState();
    renderAll();
    const now = new Date();
    const monthName = MONTH_NAMES[now.getMonth()];
    const msg = all.length === 1
      ? `"${all[0]}" generado para ${monthName}`
      : `${all.length} recurrentes generados para ${monthName}`;
    setTimeout(() => showToast(msg), 150);
  }
}

/* ---------- Shared row renderer ---------- */

function renderRecurringRows(container, list, entryType) {
  container.innerHTML = '';

  if (list.length === 0) {
    const label = entryType === 'income' ? 'ingresos fijos' : 'gastos fijos';
    container.innerHTML = `<p class="recurring-empty">todavía no hay ${label}</p>`;
    return;
  }

  list.forEach(rec => {
    const cat = getCategoryById(rec.categoryId, entryType);
    const row = document.createElement('div');
    row.className = 'recurring-row';
    row.innerHTML = `
      <div class="recurring-row-info">
        <span class="recurring-row-name">${cat.icon} ${escapeHtml(rec.name)}</span>
        <span class="recurring-row-detail">${formatMoney(rec.amount)} · día ${rec.dayOfMonth}</span>
      </div>
      <div class="recurring-row-actions">
        <button class="cat-edit rec-edit" data-rec-id="${rec.id}" data-rec-type="${entryType}">editar</button>
        <button class="recurring-toggle${rec.active ? ' active' : ''}" data-rec-id="${rec.id}" data-rec-type="${entryType}">
          ${rec.active ? 'pausar' : 'activar'}
        </button>
        <button class="cat-remove rec-remove" data-rec-id="${rec.id}" data-rec-type="${entryType}">quitar</button>
      </div>
    `;
    container.appendChild(row);
  });

  container.querySelectorAll('.rec-edit').forEach(btn => {
    btn.addEventListener('click', () => {
      const type = btn.dataset.recType;
      const list = type === 'income' ? state.recurringIncomes : state.recurringExpenses;
      const rec = list.find(r => r.id === btn.dataset.recId);
      if (rec) openEditRecurringModal(rec, type);
    });
  });

  container.querySelectorAll('.recurring-toggle').forEach(btn => {
    btn.addEventListener('click', () => {
      const type = btn.dataset.recType;
      const list = type === 'income' ? state.recurringIncomes : state.recurringExpenses;
      const rec = list.find(r => r.id === btn.dataset.recId);
      if (!rec) return;
      rec.active = !rec.active;
      saveState();
      renderRecurringManager();
      renderRecurringIncomeManager();
    });
  });

  container.querySelectorAll('.rec-remove').forEach(btn => {
    btn.addEventListener('click', () => {
      const id = btn.dataset.recId;
      const type = btn.dataset.recType;
      const hasHistory = state.entries.some(e => e.recurringId === id && e.autoGenerated);
      if (hasHistory) {
        const label = type === 'income' ? 'ingreso fijo' : 'gasto fijo';
        if (confirm(`Este ${label} ya tiene movimientos generados. ¿Querés pausarlo en vez de eliminarlo?\n\nPausar: deja de generarse en meses futuros pero conserva el historial.\nEliminar: quita la definición pero los movimientos ya generados quedan en el historial.`)) {
          const list = type === 'income' ? state.recurringIncomes : state.recurringExpenses;
          const rec = list.find(r => r.id === id);
          if (rec) rec.active = false;
        } else {
          if (!confirm('¿Confirmar eliminación? Los movimientos ya generados quedan en el historial.')) return;
          if (type === 'income') {
            state.recurringIncomes = state.recurringIncomes.filter(r => r.id !== id);
          } else {
            state.recurringExpenses = state.recurringExpenses.filter(r => r.id !== id);
          }
        }
      } else {
        if (type === 'income') {
          state.recurringIncomes = state.recurringIncomes.filter(r => r.id !== id);
        } else {
          state.recurringExpenses = state.recurringExpenses.filter(r => r.id !== id);
        }
      }
      saveState();
      renderRecurringManager();
      renderRecurringIncomeManager();
    });
  });
}

function renderRecurringManager() {
  const container = document.getElementById('recurring-manager');
  if (!container) return;
  renderRecurringRows(container, state.recurringExpenses, 'expense');
}

function renderRecurringIncomeManager() {
  const container = document.getElementById('recurring-income-manager');
  if (!container) return;
  renderRecurringRows(container, state.recurringIncomes, 'income');
}

/* ---------- Modal open/close ---------- */

function openRecurringModal() {
  editingRecurringId = null;
  editingRecurringType = 'expense';
  _openRecurringModalShared('nuevo gasto fijo', 'guardar gasto fijo');
}

function openRecurringIncomeModal() {
  editingRecurringId = null;
  editingRecurringType = 'income';
  _openRecurringModalShared('nuevo ingreso fijo', 'guardar ingreso fijo');
}

function openEditRecurringModal(rec, type) {
  editingRecurringId = rec.id;
  editingRecurringType = type;
  const label = type === 'income' ? 'ingreso fijo' : 'gasto fijo';
  _openRecurringModalShared(`editar ${label}`, 'guardar cambios', rec);
}

function _openRecurringModalShared(title, saveLabel, rec) {
  closeAllModals();
  document.querySelector('#recurring-modal-backdrop .modal-title').textContent = title;
  document.getElementById('btn-save-recurring').textContent = saveLabel;
  document.getElementById('recurring-name').value = rec ? rec.name : '';
  document.getElementById('recurring-amount').value = rec ? rec.amount : '';
  document.getElementById('recurring-day').value = rec ? rec.dayOfMonth : '';
  selectedCategoryIdForRecurring = rec ? rec.categoryId : null;
  selectedAccountIdForRecurring = rec
    ? rec.accountId
    : (state.accounts.length > 0 ? state.accounts[0].id : null);
  renderRecurringCategoryGrid();
  renderRecurringAccountGrid();
  document.getElementById('recurring-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeRecurringModal() {
  document.getElementById('recurring-modal-backdrop').hidden = true;
}

/* ---------- Category & account grids ---------- */

function openAccountFromRecurring() {
  pendingRecurringData = {
    name: document.getElementById('recurring-name').value,
    amount: document.getElementById('recurring-amount').value,
    day: document.getElementById('recurring-day').value,
    categoryId: selectedCategoryIdForRecurring,
    recurringType: editingRecurringType,
    editingRecurringId: editingRecurringId,
  };
  editingAccountId = null;
  closeAllOverlaysAndModals();
  document.getElementById('account-modal-title').textContent = 'nueva cuenta';
  document.getElementById('new-account-name').value = '';
  document.getElementById('new-account-initial-balance').value = '';
  document.getElementById('account-adjustment-section').hidden = true;
  document.getElementById('btn-save-account').textContent = 'agregar cuenta';
  selectedIconForNewAccount = ACCOUNT_ICON_OPTIONS[0];
  selectedAccountType = 'cash';
  renderAccountIconPicker();
  updateAccountTypeSelector();
  document.getElementById('account-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function restoreRecurringModal(data) {
  editingRecurringType = data.recurringType || 'expense';
  editingRecurringId = data.editingRecurringId || null;
  document.getElementById('recurring-name').value = data.name || '';
  document.getElementById('recurring-amount').value = data.amount || '';
  document.getElementById('recurring-day').value = data.day || '';
  selectedCategoryIdForRecurring = data.categoryId || null;
  renderRecurringCategoryGrid();
  renderRecurringAccountGrid();
  document.getElementById('recurring-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function renderRecurringCategoryGrid() {
  const grid = document.getElementById('recurring-category-grid');
  if (!grid) return;
  grid.innerHTML = '';
  const cats = editingRecurringType === 'income' ? state.incomeCategories : state.categories;
  cats.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryIdForRecurring === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryIdForRecurring = cat.id;
      renderRecurringCategoryGrid();
    });
    grid.appendChild(chip);
  });
}

function renderRecurringAccountGrid() {
  const grid = document.getElementById('recurring-account-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.accounts.forEach(acc => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedAccountIdForRecurring === acc.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${acc.icon}</span><span>${escapeHtml(acc.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedAccountIdForRecurring = acc.id;
      renderRecurringAccountGrid();
    });
    grid.appendChild(chip);
  });
  const addChip = document.createElement('button');
  addChip.type = 'button';
  addChip.className = 'category-chip add-new-chip';
  addChip.innerHTML = `<span class="chip-icon">＋</span><span>nueva cuenta</span>`;
  addChip.addEventListener('click', openAccountFromRecurring);
  grid.appendChild(addChip);
}

/* ---------- Save ---------- */

function saveRecurring() {
  const name = document.getElementById('recurring-name').value.trim();
  const amount = parseFloat(document.getElementById('recurring-amount').value);
  const day = parseInt(document.getElementById('recurring-day').value, 10);
  const typeLabel = editingRecurringType === 'income' ? 'ingreso fijo' : 'gasto fijo';

  if (!name) { showToast(`Ponele un nombre al ${typeLabel}`); return; }
  if (!amount || amount <= 0) { showToast('Ingresá un monto válido'); return; }
  if (!day || day < 1 || day > 28) { showToast('El día debe estar entre 1 y 28'); return; }
  if (!selectedCategoryIdForRecurring) { showToast('Elegí una categoría'); return; }
  if (!selectedAccountIdForRecurring) { showToast('Elegí una cuenta'); return; }

  const list = editingRecurringType === 'income' ? state.recurringIncomes : state.recurringExpenses;

  if (editingRecurringId) {
    const idx = list.findIndex(r => r.id === editingRecurringId);
    if (idx !== -1) {
      list[idx] = {
        ...list[idx],
        name,
        amount,
        categoryId: selectedCategoryIdForRecurring,
        accountId: selectedAccountIdForRecurring,
        dayOfMonth: day,
      };
    }
    saveState();
    closeRecurringModal();
    renderRecurringManager();
    renderRecurringIncomeManager();
    showToast(`${typeLabel.charAt(0).toUpperCase() + typeLabel.slice(1)} actualizado`);
  } else {
    list.push({
      id: uid(),
      name,
      amount,
      categoryId: selectedCategoryIdForRecurring,
      accountId: selectedAccountIdForRecurring,
      dayOfMonth: day,
      active: true,
    });
    saveState();
    closeRecurringModal();
    renderRecurringManager();
    renderRecurringIncomeManager();
    showToast(`${typeLabel.charAt(0).toUpperCase() + typeLabel.slice(1)} agregado`);
  }
}
