/* ============================================
   REPORTXLSX.JS — arma el Excel del reporte con SheetJS.
   Las hojas usan números reales (no texto formateado) para que se
   puedan sumar, filtrar y graficar en Excel.
   ============================================ */

const XLSX_MONEY_FORMAT = '#,##0.00';

function xlsxSheet(rows, widths, moneyCols) {
  const ws = XLSX.utils.aoa_to_sheet(rows);
  ws['!cols'] = widths.map(w => ({ wch: w }));
  if (moneyCols && moneyCols.length) {
    const range = XLSX.utils.decode_range(ws['!ref']);
    for (let r = range.s.r + 1; r <= range.e.r; r++) {
      moneyCols.forEach(c => {
        const cell = ws[XLSX.utils.encode_cell({ r, c })];
        if (cell && typeof cell.v === 'number') cell.z = XLSX_MONEY_FORMAT;
      });
    }
  }
  return ws;
}

function entryOriginLabel(e) {
  if (e.installmentPurchaseId) return 'cuota';
  if (e.autoGenerated) return e.type === 'income' ? 'ingreso fijo' : 'gasto fijo';
  return 'manual';
}

function buildReportXlsx(data) {
  const { range } = data;
  const wb = XLSX.utils.book_new();
  const typeLabel = { income: 'Ingreso', expense: 'Gasto', adjustment: 'Ajuste de saldo' };

  // Resumen
  const summary = [
    ['Libro de Caja - Reporte', range.label],
    ['Desde', range.startISO],
    ['Hasta', range.endISO],
    ['Generado', todayISO()],
    [],
    ['Concepto', 'Valor'],
    ['Ingresos', data.income],
    ['Gastos', data.expense],
    ['Ajustes de saldo', data.adjNet],
    ['Saldo del período', data.balance],
    ['Tasa de ahorro (%)', data.savingsRate == null ? '' : Math.round(data.savingsRate * 10) / 10],
    ['Promedio diario de gasto', data.avgDaily],
    ['Días del período', data.days],
    ['Días con registro', data.loggedDays],
    ['Movimientos confirmados', data.movements],
    ['Movimientos pendientes', data.pendingCount],
    [`Gastos hormiga (menores a ${data.ants.threshold})`, data.ants.total],
    ['Cantidad de gastos hormiga', data.ants.count],
    ['Ahorro en USD (salida en pesos)', data.saved.usd],
    ['Racha actual (días)', data.streak.current],
    ['Mejor racha (días)', data.streak.best],
  ];
  if (data.prev) {
    summary.push([], [`Período anterior (${data.prev.label})`, ''],
      ['Ingresos', data.prev.income], ['Gastos', data.prev.expense]);
  }
  const wsSummary = xlsxSheet(summary, [38, 22], [1]);
  XLSX.utils.book_append_sheet(wb, wsSummary, 'Resumen');

  // Movimientos
  const moves = state.entries
    .filter(e => e.date >= range.startISO && e.date <= range.endISO)
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date) || (a.createdAt || 0) - (b.createdAt || 0))
    .map(e => {
      const isAdj = e.type === 'adjustment';
      const cat = isAdj ? { name: 'Ajuste de saldo' } : getCategoryById(e.categoryId, e.type);
      const sub = !isAdj && e.subcategoryId ? getSubcategoryById(e.categoryId, e.subcategoryId, e.type) : null;
      const signed = e.type === 'expense' ? -e.amount : e.amount;
      const split = e.split && e.split.enabled ? e.split : null;
      return [
        e.date, typeLabel[e.type] || e.type, cat.name, sub ? sub.name : '', e.note || '',
        getAccountById(e.accountId).name, signed, getEntryTags(e).map(formatTag).join(', '),
        split ? split.otherPartyName : '', split ? split.otherShare : '',
        split ? (split.settled ? 'saldado' : 'por cobrar') : '',
        e.pending ? 'pendiente' : 'confirmado', entryOriginLabel(e),
      ];
    });
  const wsMoves = xlsxSheet(
    [['Fecha', 'Tipo', 'Categoría', 'Subcategoría', 'Nota', 'Cuenta', 'Monto', 'Etiquetas',
      'Compartido con', 'Parte del otro', 'Cobro', 'Estado', 'Origen'], ...moves],
    [12, 15, 20, 18, 30, 16, 14, 24, 16, 14, 12, 12, 12],
    [6, 9],
  );
  wsMoves['!autofilter'] = { ref: wsMoves['!ref'] };
  XLSX.utils.book_append_sheet(wb, wsMoves, 'Movimientos');

  // Por categoría
  const cats = [['Categoría', 'Tipo', 'Monto', '% del total', 'Movimientos']];
  data.categories.forEach(c => cats.push([c.name, 'Gasto', c.amount, Math.round(c.pct * 10) / 10, c.count]));
  data.incomeCategories.forEach(c => cats.push([c.name, 'Ingreso', c.amount, Math.round(c.pct * 10) / 10, '']));
  XLSX.utils.book_append_sheet(wb, xlsxSheet(cats, [26, 12, 16, 12, 13], [2]), 'Por categoría');

  // Evolución
  const evoHead = data.seriesKind === 'day' ? 'Día' : (data.seriesKind === 'year' ? 'Año' : 'Mes');
  const evo = [[evoHead, 'Ingresos', 'Gastos', 'Saldo']];
  data.series.forEach(r => evo.push([r.label, r.income, r.expense, r.income - r.expense]));
  XLSX.utils.book_append_sheet(wb, xlsxSheet(evo, [14, 16, 16, 16], [1, 2, 3]), 'Evolución');

  // Por día de la semana
  const wk = [['Día', 'Gasto', 'Movimientos']];
  data.weekdays.forEach(w => wk.push([w.label, w.amount, w.count]));
  XLSX.utils.book_append_sheet(wb, xlsxSheet(wk, [14, 16, 13], [1]), 'Día de la semana');

  // Cuentas
  const acc = [['Cuenta', 'Ingresos del período', 'Gastos del período', 'Saldo actual']];
  data.accounts.forEach(a => acc.push([a.name, a.income, a.expense, a.balanceNow]));
  XLSX.utils.book_append_sheet(wb, xlsxSheet(acc, [22, 20, 20, 16], [1, 2, 3]), 'Cuentas');

  // Transferencias
  const transfers = (state.transfers || [])
    .filter(t => t.date >= range.startISO && t.date <= range.endISO)
    .slice().sort((a, b) => a.date.localeCompare(b.date))
    .map(t => [t.date, getAccountById(t.fromAccountId).name, getAccountById(t.toAccountId).name, t.amount, t.note || '']);
  if (transfers.length) {
    XLSX.utils.book_append_sheet(wb,
      xlsxSheet([['Fecha', 'Desde', 'Hacia', 'Monto', 'Nota'], ...transfers], [12, 18, 18, 14, 30], [3]),
      'Transferencias');
  }

  // Presupuestos (solo en reportes de un mes)
  if (data.budgets.length) {
    const bud = [['Categoría', 'Límite', 'Gastado', '% usado']];
    data.budgets.forEach(b => bud.push([b.name, b.limit, b.spent, b.limit > 0 ? Math.round((b.spent / b.limit) * 100) : '']));
    XLSX.utils.book_append_sheet(wb, xlsxSheet(bud, [24, 16, 16, 11], [1, 2]), 'Presupuestos');
  }

  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  return new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
}
