/* ============================================
   SAVINGS.JS — aviso de ahorro del mes y cálculo de cuánto se podría ahorrar
   - "Ahorro libre" = depósitos de ahorro en USD (state.dollarSavings). El plan de
     inversión es ahorro de largo plazo y se muestra aparte: no cuenta para el
     piso ni para el aviso (el ahorro de corto/mediano plazo es otro).
   - "Podrías ahorrar hoy" se calcula con la plata disponible, no con un
     porcentaje fijo, así se adapta a meses buenos y malos:
       lo que tenés ahora − pendientes del mes − gasto variable que falta − colchón
   Es una estimación: el usuario decide qué hacer con ella.
   ============================================ */

const SAVINGS_NUDGE_FROM_DAY = 15;
const SAVINGS_HISTORY_MONTHS = 3;

function getSavingsSettings() {
  const s = state.savingsSettings || {};
  return {
    floorUSD: s.floorUSD > 0 ? s.floorUSD : 0,
    idealPct: s.idealPct > 0 ? s.idealPct : 20,
    cushionPct: s.cushionPct >= 0 ? s.cushionPct : 15,
  };
}

function sumAmountUSDInMonth(list, date) {
  return (list || []).filter(x => x.date && isSameMonth(x.date, date)).reduce((s, x) => s + (x.amountUSD || 0), 0);
}

function planContributedUSDInMonth(date) {
  return (state.investmentPlans || []).reduce((s, p) => s + sumAmountUSDInMonth(p.contributions, date), 0);
}

function isVariableExpense(e) {
  return e.type === 'expense' && !e.pending && !e.autoGenerated && !e.installmentPurchaseId && e.categoryId !== 'ahorro-usd';
}

function computeSavingsOverview(now) {
  now = now || new Date();
  const settings = getSavingsSettings();
  const rate = getLastExchangeRate();
  const toUSD = ars => (rate ? ars / rate : null);

  const dim = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
  const daysElapsed = now.getDate();
  const monthEndISO = isoFromDate(new Date(now.getFullYear(), now.getMonth(), dim));

  // Meses anteriores con movimiento, para saber cómo gasta y cuánto ingresa normalmente.
  const history = [];
  for (let i = 1; i <= SAVINGS_HISTORY_MONTHS; i++) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    const entries = getEntriesForMonth(d).filter(e => !e.pending);
    const spend = entries.filter(e => e.type === 'expense' && e.categoryId !== 'ahorro-usd');
    if (spend.length === 0) continue;
    history.push({
      variable: entries.filter(isVariableExpense).reduce((s, e) => s + e.amount, 0),
      total: spend.reduce((s, e) => s + e.amount, 0),
      income: entries.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0),
    });
  }
  const avg = key => (history.length ? history.reduce((s, h) => s + h[key], 0) / history.length : null);
  const avgVariable = avg('variable');
  const avgTotal = avg('total');
  const avgIncome = avg('income');

  const thisMonth = getEntriesForMonth(now).filter(e => !e.pending);
  const variableSoFar = thisMonth.filter(isVariableExpense).reduce((s, e) => s + e.amount, 0);
  const paidFixedSoFar = thisMonth
    .filter(e => e.type === 'expense' && e.categoryId !== 'ahorro-usd' && !isVariableExpense(e))
    .reduce((s, e) => s + e.amount, 0);
  const incomeSoFar = thisMonth.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0);

  // Fijos y cuotas de ESTE mes que todavía no pagaste. Los pendientes de meses anteriores no se
  // suman: casi siempre son pagos que se hicieron y quedaron sin confirmar, y inflaban el cálculo.
  const monthStartISO = isoFromDate(new Date(now.getFullYear(), now.getMonth(), 1));
  const pendingNow = state.entries.filter(e => e.pending && e.type === 'expense' && e.date >= monthStartISO && e.date <= monthEndISO);
  const pendingTotal = pendingNow.reduce((s, e) => s + e.amount, 0);
  const staleOld = state.entries.filter(e => e.pending && e.type === 'expense' && e.date < monthStartISO);

  // Gasto variable del mes: lo más alto entre tu promedio y tu ritmo actual (a propósito conservador).
  const paceProjection = daysElapsed >= 5 ? (variableSoFar / daysElapsed) * dim : null;
  const projections = [avgVariable, paceProjection].filter(v => v != null);
  const projectedVariable = projections.length ? Math.max(...projections) : null;
  const enoughData = projectedVariable != null;
  const remainingVariable = enoughData ? Math.max(0, projectedVariable - variableSoFar) : 0;

  const monthlySpendRef = avgTotal != null
    ? avgTotal
    : (enoughData ? projectedVariable + paidFixedSoFar + pendingTotal : 0);
  const cushion = (settings.cushionPct / 100) * monthlySpendRef;

  const cash = state.accounts.reduce((s, a) => s + getAccountBalance(a.id), 0);
  const marginARS = cash - pendingTotal - remainingVariable - cushion;
  const capacityARS = enoughData ? Math.max(0, marginARS) : 0;

  const incomeRef = incomeSoFar > 0 ? incomeSoFar : (avgIncome || 0);
  const idealARS = incomeRef > 0 ? (settings.idealPct / 100) * incomeRef : null;

  return {
    now, settings, rate, daysElapsed, daysInMonth: dim, enoughData,
    // Los euros se pasan a dólares (vía pesos) para compararlos con el piso, que está en USD.
    savedUSD: (state.dollarSavings || [])
      .filter(d => d.date && isSameMonth(d.date, now))
      .reduce((s, d) => s + depositUSDEquivalent(d, rate), 0),
    planUSD: planContributedUSDInMonth(now),
    cash, pendingTotal, pendingCount: pendingNow.length, staleCount: staleOld.length,
    staleTotal: staleOld.reduce((s, e) => s + e.amount, 0), projectedVariable, remainingVariable, cushion, marginARS,
    capacityARS, capacityUSD: toUSD(capacityARS),
    idealARS, idealUSD: idealARS == null ? null : toUSD(idealARS),
    monthlySpendRef,
  };
}

/* ---------- Aviso en el Inicio ---------- */

function getSavingsNudge(ov) {
  const monthKey = yearMonthKey(ov.now);
  if (state.savingsNudgeDismissed === monthKey) return null;
  if (ov.daysElapsed < SAVINGS_NUDGE_FROM_DAY) return null;

  const floor = ov.settings.floorUSD;
  const reachedFloor = floor > 0 ? ov.savedUSD >= floor : ov.savedUSD > 0;
  if (reachedFloor) return null;

  let title;
  if (ov.savedUSD <= 0) {
    title = ov.planUSD > 0
      ? 'Este mes solo pusiste el plan: todavía no ahorraste aparte'
      : 'Este mes todavía no ahorraste';
  } else {
    title = `Llevás ${formatUSD(ov.savedUSD)} de tu piso de ${formatUSD(floor)}`;
  }

  let sub;
  if (!ov.enoughData) {
    sub = 'Todavía hay pocos datos para estimar cuánto podrías ahorrar';
  } else if (ov.capacityARS <= 0) {
    sub = 'Hoy el margen está ajustado: no hace falta forzarlo';
  } else if (ov.capacityUSD != null) {
    sub = `Hoy podrías ahorrar hasta ${formatUSD(Math.floor(ov.capacityUSD))} sin comprometer el mes`;
  } else {
    sub = `Hoy podrías ahorrar hasta ${formatMoney(ov.capacityARS)} sin comprometer el mes`;
  }
  return { title, sub };
}

function renderSavingsCard() {
  const card = document.getElementById('savings-nudge');
  if (!card) return;
  const nudge = getSavingsNudge(computeSavingsOverview());
  card.hidden = !nudge;
  if (nudge) {
    document.getElementById('savings-nudge-title').textContent = nudge.title;
    document.getElementById('savings-nudge-sub').textContent = nudge.sub;
  }
}

function dismissSavingsNudge() {
  state.savingsNudgeDismissed = yearMonthKey(new Date());
  saveState();
  renderSavingsCard();
}

/* ---------- Modal con el cálculo ---------- */

function openSavingsModal() {
  closeAllModals();
  const ov = computeSavingsOverview();
  const { floorUSD, idealPct, cushionPct } = ov.settings;
  const usd = v => (v == null ? '' : formatUSD(v));

  const row = (label, amount, sub, sign) => `
    <div class="savings-row">
      <div class="savings-row-detail">
        <div class="savings-row-label">${label}</div>
        ${sub ? `<div class="savings-row-sub">${sub}</div>` : ''}
      </div>
      <div class="savings-row-amount${sign === '-' ? ' minus' : ''}">${sign === '-' ? '−' : ''}${formatMoney(Math.abs(amount))}</div>
    </div>`;

  let capacityBlock;
  if (!ov.enoughData) {
    capacityBlock = `<p class="savings-note">Todavía hay pocos datos para estimarlo: necesito un mes anterior con gastos, o al menos 5 días de movimientos este mes.</p>`;
  } else {
    const big = ov.capacityARS <= 0
      ? 'Sin margen por ahora'
      : (ov.capacityUSD != null ? formatUSD(Math.floor(ov.capacityUSD)) : formatMoney(ov.capacityARS));
    const bigSub = ov.capacityARS > 0 && ov.capacityUSD != null
      ? `≈ ${formatMoney(ov.capacityARS)} al dólar de $ ${ov.rate.toLocaleString('es-AR')}`
      : (ov.capacityARS > 0 ? '' : 'Tu plata disponible alcanza justo para lo que viene este mes');
    capacityBlock = `
      <div class="savings-capacity">
        <span class="savings-capacity-label">Podrías ahorrar hoy hasta</span>
        <span class="savings-capacity-value">${big}</span>
        ${bigSub ? `<span class="savings-capacity-sub">${bigSub}</span>` : ''}
      </div>
      <p class="report-subtitle">Cómo se calcula</p>
      ${row('Tenés ahora', ov.cash, 'saldo de todas tus cuentas', '+')}
      ${row('Fijos y cuotas por pagar', ov.pendingTotal,
        ov.pendingCount ? `${ov.pendingCount} ${ov.pendingCount === 1 ? 'pendiente' : 'pendientes'} de este mes` : 'nada pendiente este mes', '-')}
      ${row('Gasto variable que falta', ov.remainingVariable, 'según tu ritmo y tus últimos meses', '-')}
      ${row(`Colchón de seguridad (${cushionPct} %)`, ov.cushion, 'de un mes de gastos, para imprevistos', '-')}
      <div class="savings-row savings-row-total">
        <div class="savings-row-detail"><div class="savings-row-label">Margen</div></div>
        <div class="savings-row-amount">${formatMoney(Math.max(0, ov.marginARS))}</div>
      </div>`;
  }

  const planLine = ov.planUSD > 0
    ? `<p class="savings-note">Además pusiste ${formatUSD(ov.planUSD)} en el plan. Es ahorro de largo plazo, así que no cuenta acá.</p>`
    : '';
  const floorLine = floorUSD > 0
    ? `<div class="savings-progress" role="img" aria-label="Ahorrado ${Math.round(Math.min(100, (ov.savedUSD / floorUSD) * 100))} por ciento del piso"><div class="savings-progress-fill" style="width:${Math.min(100, (ov.savedUSD / floorUSD) * 100)}%"></div></div>
       <p class="savings-note">Tu piso es ${formatUSD(floorUSD)} por mes${ov.savedUSD >= floorUSD ? ' · ¡cumplido!' : ''}.</p>`
    : '';
  const staleLine = ov.staleCount > 0
    ? `<p class="savings-note">Tenés ${ov.staleCount} ${ov.staleCount === 1 ? 'pendiente' : 'pendientes'} de meses anteriores (${formatMoney(ov.staleTotal)}) sin confirmar. No se cuentan acá; si ya los pagaste, confirmalos en Pendientes, mirando el mes anterior.</p>`
    : '';
  const idealLine = ov.idealARS != null
    ? `<p class="savings-note">Ideal: ${idealPct} % de tus ingresos = ${ov.idealUSD != null ? formatUSD(Math.round(ov.idealUSD)) : formatMoney(ov.idealARS)}. Lo cambiás en Ajustes.</p>`
    : '';

  document.getElementById('savings-body').innerHTML = `
    <div class="savings-saved">
      <span class="savings-saved-label">Ahorrado este mes (aparte del plan)</span>
      <span class="savings-saved-value">${formatUSD(ov.savedUSD)}</span>
    </div>
    ${floorLine}
    ${planLine}
    ${capacityBlock}
    ${staleLine}
    ${idealLine}
    <p class="savings-note savings-disclaimer">Es una estimación con tus propios datos, no una recomendación financiera. Vos decidís cuánto ahorrar.</p>
  `;

  // Atajos que abren el depósito con el monto cargado (siempre editable).
  const chips = document.getElementById('savings-chips');
  chips.innerHTML = '';
  const options = [];
  if (ov.rate) {
    if (floorUSD > 0) options.push({ label: `Mi piso · ${formatUSD(floorUSD)}`, usd: floorUSD });
    if (ov.idealUSD != null) options.push({ label: `Ideal · ${formatUSD(Math.round(ov.idealUSD))}`, usd: Math.round(ov.idealUSD) });
    if (ov.capacityUSD != null && ov.capacityUSD >= 1) options.push({ label: `Máximo · ${formatUSD(Math.floor(ov.capacityUSD))}`, usd: Math.floor(ov.capacityUSD) });
  }
  chips.hidden = options.length === 0;
  options.forEach(opt => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip';
    chip.textContent = opt.label;
    chip.addEventListener('click', () => {
      closeSavingsModal();
      openDollarModal(opt.usd);
    });
    chips.appendChild(chip);
  });
  document.getElementById('savings-chips-label').hidden = options.length === 0;

  document.getElementById('savings-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeSavingsModal() {
  document.getElementById('savings-modal-backdrop').hidden = true;
}

/* ---------- Ajustes ---------- */

function renderSavingsSettings() {
  const s = getSavingsSettings();
  const set = (id, v) => { const el = document.getElementById(id); if (el) el.value = v; };
  set('savings-floor-input', s.floorUSD || '');
  set('savings-ideal-input', s.idealPct);
  set('savings-cushion-input', s.cushionPct);
}

function saveSavingsSettings() {
  const floorRaw = document.getElementById('savings-floor-input').value;
  const floor = floorRaw === '' ? 0 : parseFloat(floorRaw);
  const ideal = parseFloat(document.getElementById('savings-ideal-input').value);
  const cushion = parseFloat(document.getElementById('savings-cushion-input').value);

  if (isNaN(floor) || floor < 0) { showToast('El piso tiene que ser 0 o más'); return; }
  if (isNaN(ideal) || ideal <= 0 || ideal > 100) { showToast('El ideal tiene que estar entre 1 y 100 %'); return; }
  if (isNaN(cushion) || cushion < 0 || cushion > 100) { showToast('El colchón tiene que estar entre 0 y 100 %'); return; }

  state.savingsSettings = { floorUSD: floor, idealPct: ideal, cushionPct: cushion };
  saveState();
  renderAll();
  showToast('Ahorro actualizado');
}

// Texto del acceso desde Metas: lo ahorrado este mes y, si se puede estimar, cuánto más podría ahorrarse.
function savingsLinkText() {
  const ov = computeSavingsOverview();
  const parts = [`Este mes (aparte del plan): ${formatUSD(ov.savedUSD)}`];
  if (ov.enoughData && ov.capacityARS > 0) {
    parts.push(ov.capacityUSD != null
      ? `podrías hasta ${formatUSD(Math.floor(ov.capacityUSD))}`
      : `podrías hasta ${formatMoney(ov.capacityARS)}`);
  }
  return `${parts.join(' · ')} · ver cálculo`;
}
