/* ============================================
   LIBRO DE CAJA — app.js
   Vanilla JS, localStorage persistence
   ============================================ */

const STORAGE_KEY = 'libro-caja-data-v1';

const DEFAULT_CATEGORIES = [
  { id: 'comida', name: 'Comida', icon: '🍴' },
  { id: 'transporte', name: 'Transporte', icon: '🚌' },
  { id: 'servicios', name: 'Servicios', icon: '💡' },
  { id: 'ocio', name: 'Ocio', icon: '🎮' },
  { id: 'salud', name: 'Salud', icon: '💊' },
  { id: 'hogar', name: 'Hogar', icon: '🏠' },
  { id: 'ropa', name: 'Ropa', icon: '👕' },
  { id: 'educacion', name: 'Educación', icon: '📚' },
  { id: 'otros', name: 'Otros', icon: '◆' },
];

const DEFAULT_INCOME_CATEGORIES = [
  { id: 'sueldo', name: 'Sueldo', icon: '💼' },
  { id: 'freelance', name: 'Freelance', icon: '💻' },
  { id: 'regalo', name: 'Regalo', icon: '🎁' },
  { id: 'venta', name: 'Venta', icon: '🏷️' },
  { id: 'otros-ing', name: 'Otros', icon: '◆' },
];

const ICON_OPTIONS = ['🍴','🚌','💡','🎮','💊','🏠','👕','📚','◆','🐾','✈️','📱','🎓','🛒','⚽','🎵','🔧','💼','💻','🎁','🏷️','💰','📦','☕'];

const DEFAULT_ACCOUNTS = [
  { id: 'cash',    name: 'Efectivo',     icon: '💵', type: 'cash' },
  { id: 'bank',    name: 'Banco',        icon: '🏦', type: 'bank' },
  { id: 'digital', name: 'Mercado Pago', icon: '📲', type: 'digital' },
];

const ACCOUNT_ICON_OPTIONS = ['💵','🏦','📲','💳','🏧','💰','💼','📱','🪙','💎','🔑','⭐'];

const MONTH_NAMES = ['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'];
const DAY_NAMES_SHORT = ['dom','lun','mar','mié','jue','vie','sáb'];

/* ---------- State ---------- */

let state = {
  entries: [],            // {id, type, amount, categoryId, accountId, note, date, recurringId?, autoGenerated?}
  categories: DEFAULT_CATEGORIES,
  incomeCategories: DEFAULT_INCOME_CATEGORIES,
  goals: [],               // {id, name, target, current}
  accounts: [...DEFAULT_ACCOUNTS],
  recurringExpenses: [],   // {id, name, amount, categoryId, accountId, dayOfMonth, active}
  budgets: [],             // {categoryId, monthlyLimit}
  streak: { count: 0, lastDate: null },
};

let viewDate = new Date();        // month currently shown in ledger
let currentFilter = 'all';
let currentEntryType = 'expense';
let selectedCategoryId = null;
let selectedAccountId = null;
let selectedIconForNewCategory = ICON_OPTIONS[0];
let selectedIconForNewAccount = ACCOUNT_ICON_OPTIONS[0];
let selectedAccountType = 'cash';
let selectedCategoryIdForRecurring = null;
let selectedAccountIdForRecurring = null;
let selectedCategoryIdForBudget = null;

/* ---------- Persistence ---------- */

function loadState() {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw);
      state = Object.assign(state, parsed);
    }
    if (!state.accounts || state.accounts.length === 0) {
      state.accounts = [...DEFAULT_ACCOUNTS];
    }
    if (!state.recurringExpenses) {
      state.recurringExpenses = [];
    }
    if (!state.budgets) {
      state.budgets = [];
    }
    const needsMigration = state.entries.some(e => !e.accountId);
    if (needsMigration) {
      if (!state.accounts.find(a => a.id === 'general')) {
        state.accounts = [{ id: 'general', name: 'General', icon: '◆', type: 'cash' }, ...state.accounts];
      }
      state.entries = state.entries.map(e => e.accountId ? e : { ...e, accountId: 'general' });
    }
  } catch (e) {
    console.error('No se pudo cargar el estado guardado', e);
  }
}

function saveState() {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  } catch (e) {
    console.error('No se pudo guardar el estado', e);
    showToast('No se pudo guardar — revisá el espacio disponible');
  }
}

/* ---------- Helpers ---------- */

function uid() {
  return Date.now().toString(36) + Math.random().toString(36).slice(2, 7);
}

function formatMoney(n) {
  const rounded = Math.round(n);
  return '$ ' + rounded.toLocaleString('es-AR');
}

function todayISO() {
  const d = new Date();
  return isoFromDate(d);
}

function isoFromDate(d) {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function dateFromISO(iso) {
  const [y, m, d] = iso.split('-').map(Number);
  return new Date(y, m - 1, d);
}

function isSameMonth(iso, date) {
  const d = dateFromISO(iso);
  return d.getFullYear() === date.getFullYear() && d.getMonth() === date.getMonth();
}

function monthLabel(date) {
  return `${MONTH_NAMES[date.getMonth()]} ${date.getFullYear()}`;
}

function getCategoryById(id, type) {
  const list = type === 'income' ? state.incomeCategories : state.categories;
  return list.find(c => c.id === id) || { id, name: id, icon: '◆' };
}

function getAccountById(id) {
  return state.accounts.find(a => a.id === id) || { id, name: 'General', icon: '◆', type: 'cash' };
}

function showToast(msg) {
  const toast = document.getElementById('toast');
  toast.textContent = msg;
  toast.classList.add('show');
  clearTimeout(showToast._t);
  showToast._t = setTimeout(() => toast.classList.remove('show'), 2200);
}

/* ============================================
   OVERLAY / MODAL COORDINATION
   ============================================ */

const VIEW_OVERLAY_IDS = ['view-stats', 'view-goals', 'view-settings'];
const MODAL_OVERLAY_IDS = ['modal-backdrop', 'goal-modal-backdrop', 'cat-modal-backdrop', 'account-modal-backdrop', 'recurring-modal-backdrop', 'budget-modal-backdrop'];

function updateNavForLedger() {
  document.querySelectorAll('.nav-item').forEach(item => {
    item.classList.toggle('active', item.dataset.view === 'ledger');
  });
}

function closeAllModals() {
  MODAL_OVERLAY_IDS.forEach(id => { document.getElementById(id).hidden = true; });
}

function closeAllOverlaysAndModals() {
  VIEW_OVERLAY_IDS.forEach(id => { document.getElementById(id).hidden = true; });
  MODAL_OVERLAY_IDS.forEach(id => { document.getElementById(id).hidden = true; });
  updateNavForLedger();
}

function getTopmostOverlay() {
  for (const id of MODAL_OVERLAY_IDS) {
    const el = document.getElementById(id);
    if (el && !el.hidden) return el;
  }
  for (const id of VIEW_OVERLAY_IDS) {
    const el = document.getElementById(id);
    if (el && !el.hidden) return el;
  }
  return null;
}

function closeTopmostOverlay() {
  const el = getTopmostOverlay();
  if (!el) return;
  const id = el.id;
  if (id === 'modal-backdrop') closeAddModal();
  else if (id === 'goal-modal-backdrop') closeGoalModal();
  else if (id === 'cat-modal-backdrop') closeCategoryModal();
  else { el.hidden = true; updateNavForLedger(); }
}

/* ============================================
   RENDER: SUMMARY CARD
   ============================================ */

function getEntriesForMonth(date) {
  return state.entries.filter(e => isSameMonth(e.date, date));
}

function renderSummary() {
  document.getElementById('current-month-label').textContent = monthLabel(viewDate);
  const monthEntries = getEntriesForMonth(viewDate);

  const income = monthEntries.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0);
  const expense = monthEntries.filter(e => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
  const balance = income - expense;

  const balanceEl = document.getElementById('month-balance');
  balanceEl.textContent = formatMoney(balance);
  balanceEl.classList.toggle('negative', balance < 0);

  document.getElementById('month-income').textContent = formatMoney(income);
  document.getElementById('month-expense').textContent = formatMoney(expense);
  renderAccountBreakdown(monthEntries);
}

function renderAccountBreakdown(monthEntries) {
  const container = document.getElementById('account-breakdown');
  if (!container) return;

  const byAccount = {};
  monthEntries.forEach(e => {
    const key = e.accountId || 'general';
    byAccount[key] = (byAccount[key] || 0) + (e.type === 'income' ? e.amount : -e.amount);
  });

  const accountsUsed = Object.keys(byAccount);
  if (accountsUsed.length <= 1) { container.hidden = true; return; }

  container.hidden = false;
  container.innerHTML = '';
  accountsUsed.forEach(accId => {
    const acc = getAccountById(accId);
    const balance = byAccount[accId];
    const row = document.createElement('div');
    row.className = 'account-balance-row';
    row.innerHTML = `
      <span class="account-balance-name">${acc.icon} ${escapeHtml(acc.name)}</span>
      <span class="account-balance-amount${balance < 0 ? ' negative' : ''}">${formatMoney(balance)}</span>
    `;
    container.appendChild(row);
  });
}

/* ============================================
   RENDER: STREAK
   ============================================ */

function computeStreak() {
  const datesWithEntries = new Set(state.entries.map(e => e.date));
  if (datesWithEntries.size === 0) return 0;

  let streak = 0;
  let cursor = new Date();

  if (!datesWithEntries.has(isoFromDate(cursor))) {
    cursor.setDate(cursor.getDate() - 1);
  }

  while (datesWithEntries.has(isoFromDate(cursor))) {
    streak++;
    cursor.setDate(cursor.getDate() - 1);
  }
  return streak;
}

function renderStreak() {
  const streak = computeStreak();
  document.getElementById('streak-count').textContent = streak;

  const todayHasEntry = state.entries.some(e => e.date === todayISO());
  const badge = document.getElementById('streak-today-badge');
  badge.textContent = todayHasEntry ? 'hoy: anotado ✓' : 'hoy: pendiente';
  badge.classList.toggle('done', todayHasEntry);

  const flame = document.getElementById('streak-flame');
  flame.style.opacity = streak > 0 ? '1' : '0.35';
}

/* ============================================
   RENDER: SUGGESTIONS
   ============================================ */

function renderSuggestion() {
  const banner = document.getElementById('suggestion-banner');
  const textEl = document.getElementById('suggestion-text');
  const suggestion = computeSuggestion();

  if (!suggestion) {
    banner.hidden = true;
    return;
  }
  banner.hidden = false;
  textEl.textContent = suggestion;
}

function computeSuggestion() {
  const now = new Date();
  const thisMonthEntries = getEntriesForMonth(now);
  const lastMonthDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const lastMonthEntries = getEntriesForMonth(lastMonthDate);

  if (thisMonthEntries.length === 0 && state.entries.length === 0) {
    return null;
  }

  const streak = computeStreak();
  const todayHasEntry = state.entries.some(e => e.date === todayISO());
  if (streak >= 3 && !todayHasEntry) {
    return `Llevás ${streak} días seguidos anotando. No cortes la racha — sumá el movimiento de hoy.`;
  }

  // Budget warning: flag first category that's >= 90% of its limit
  if (state.budgets && state.budgets.length > 0) {
    const monthExpenses = thisMonthEntries.filter(e => e.type === 'expense');
    for (const budget of state.budgets) {
      const spent = monthExpenses
        .filter(e => e.categoryId === budget.categoryId)
        .reduce((s, e) => s + e.amount, 0);
      const budgetPct = (spent / budget.monthlyLimit) * 100;
      if (budgetPct >= 90) {
        const cat = getCategoryById(budget.categoryId, 'expense');
        const label = budgetPct >= 100 ? 'superó' : `llegó al ${Math.round(budgetPct)}% de`;
        return `${cat.name} ${label} su presupuesto mensual (${formatMoney(spent)} de ${formatMoney(budget.monthlyLimit)}).`;
      }
    }
  }

  const catTotals = (entries) => {
    const map = {};
    entries.filter(e => e.type === 'expense').forEach(e => {
      map[e.categoryId] = (map[e.categoryId] || 0) + e.amount;
    });
    return map;
  };
  const thisCat = catTotals(thisMonthEntries);
  const lastCat = catTotals(lastMonthEntries);

  let biggestIncrease = null;
  for (const catId in thisCat) {
    if (lastCat[catId] && lastCat[catId] > 0) {
      const pctChange = ((thisCat[catId] - lastCat[catId]) / lastCat[catId]) * 100;
      if (pctChange > 20 && (!biggestIncrease || pctChange > biggestIncrease.pct)) {
        biggestIncrease = { catId, pct: pctChange };
      }
    }
  }
  if (biggestIncrease) {
    const cat = getCategoryById(biggestIncrease.catId, 'expense');
    return `Gastaste ${Math.round(biggestIncrease.pct)}% más en ${cat.name.toLowerCase()} que el mes pasado.`;
  }

  const income = thisMonthEntries.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0);
  const expense = thisMonthEntries.filter(e => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
  if (income > 0) {
    const rate = ((income - expense) / income) * 100;
    if (rate < 0) {
      return `Este mes gastaste más de lo que ingresó. Revisá en reportes qué categoría pesó más.`;
    }
    if (rate > 0 && rate < 10) {
      return `Tu tasa de ahorro este mes es ${Math.round(rate)}%. Cualquier recorte chico en gastos variables suma.`;
    }
  }

  if (state.goals.length > 0) {
    const g = state.goals[0];
    const pct = Math.min(100, Math.round((g.current / g.target) * 100));
    if (pct < 100) {
      return `Vas ${pct}% del camino hacia tu meta "${g.name}". Seguí así.`;
    }
  }

  return null;
}

/* ============================================
   RENDER: LEDGER LIST
   ============================================ */

function renderLedger() {
  const listEl = document.getElementById('ledger-list');
  const emptyEl = document.getElementById('empty-state');
  listEl.innerHTML = '';

  let entries = getEntriesForMonth(viewDate);
  if (currentFilter !== 'all') entries = entries.filter(e => e.type === currentFilter);

  if (entries.length === 0) {
    emptyEl.hidden = false;
    return;
  }
  emptyEl.hidden = true;

  // group by date desc
  const byDate = {};
  entries.forEach(e => {
    if (!byDate[e.date]) byDate[e.date] = [];
    byDate[e.date].push(e);
  });
  const sortedDates = Object.keys(byDate).sort((a, b) => b.localeCompare(a));

  sortedDates.forEach(dateISO => {
    const group = document.createElement('div');
    group.className = 'ledger-day-group';

    const label = document.createElement('div');
    label.className = 'ledger-day-label';
    label.textContent = formatDayLabel(dateISO);
    group.appendChild(label);

    byDate[dateISO]
      .sort((a, b) => (b.createdAt || 0) - (a.createdAt || 0))
      .forEach(entry => group.appendChild(renderEntryRow(entry)));

    listEl.appendChild(group);
  });
}

function formatDayLabel(iso) {
  const d = dateFromISO(iso);
  const today = todayISO();
  const yesterday = isoFromDate(new Date(Date.now() - 86400000));
  if (iso === today) return 'hoy';
  if (iso === yesterday) return 'ayer';
  return `${DAY_NAMES_SHORT[d.getDay()]} ${d.getDate()} de ${MONTH_NAMES[d.getMonth()]}`;
}

function renderEntryRow(entry) {
  const cat = getCategoryById(entry.categoryId, entry.type);
  const acc = getAccountById(entry.accountId);
  const row = document.createElement('div');
  row.className = 'ledger-entry';
  const subtitleParts = [];
  if (entry.autoGenerated) subtitleParts.push('↻');
  if (entry.note) subtitleParts.push(escapeHtml(entry.note));
  if (state.accounts.length > 1) subtitleParts.push(`${acc.icon} ${escapeHtml(acc.name)}`);
  const subtitle = subtitleParts.join(' · ');
  row.innerHTML = `
    <div class="entry-icon ${entry.type}">${cat.icon}</div>
    <div class="entry-detail">
      <p class="entry-category">${escapeHtml(cat.name)}</p>
      ${subtitle ? `<p class="entry-note">${subtitle}</p>` : ''}
    </div>
    <div class="entry-amount ${entry.type}">${entry.type === 'expense' ? '−' : '+'}${formatMoney(entry.amount)}</div>
  `;
  row.addEventListener('click', () => {
    if (confirm(`¿Borrar este movimiento de ${cat.name}?`)) {
      deleteEntry(entry.id);
    }
  });
  return row;
}

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

function deleteEntry(id) {
  state.entries = state.entries.filter(e => e.id !== id);
  saveState();
  renderAll();
  showToast('Movimiento borrado');
}

/* ============================================
   RENDER ALL (main ledger view)
   ============================================ */

function renderAll() {
  renderSummary();
  renderStreak();
  renderSuggestion();
  renderLedger();
}

/* ============================================
   RECURRING EXPENSES — auto-generation
   ============================================ */

function processRecurringExpenses() {
  if (!state.recurringExpenses || state.recurringExpenses.length === 0) return;

  const now = new Date();
  const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}`;
  const generated = [];

  state.recurringExpenses.forEach(rec => {
    if (!rec.active) return;
    const alreadyExists = state.entries.some(
      e => e.recurringId === rec.id && e.date.startsWith(monthKey)
    );
    if (alreadyExists) return;

    const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
    const day = Math.min(rec.dayOfMonth, daysInMonth);
    const dateISO = `${monthKey}-${String(day).padStart(2, '0')}`;

    state.entries.push({
      id: uid(),
      type: 'expense',
      amount: rec.amount,
      categoryId: rec.categoryId,
      accountId: rec.accountId,
      note: rec.name,
      date: dateISO,
      createdAt: Date.now(),
      recurringId: rec.id,
      autoGenerated: true,
    });
    generated.push(rec.name);
  });

  if (generated.length > 0) {
    saveState();
    renderAll();
    const monthName = MONTH_NAMES[now.getMonth()];
    const msg = generated.length === 1
      ? `Gasto fijo "${generated[0]}" generado para ${monthName}`
      : `${generated.length} gastos fijos generados para ${monthName}`;
    setTimeout(() => showToast(msg), 150);
  }
}

/* ============================================
   MODAL: ADD ENTRY
   ============================================ */

function openAddModal() {
  closeAllOverlaysAndModals();
  currentEntryType = 'expense';
  selectedCategoryId = null;
  selectedAccountId = state.accounts.length > 0 ? state.accounts[0].id : null;
  document.getElementById('input-amount').value = '';
  document.getElementById('input-note').value = '';
  document.getElementById('input-date').value = todayISO();
  setEntryType('expense');
  renderCategoryGrid();
  renderAccountGrid();
  document.getElementById('modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
  setTimeout(() => document.getElementById('input-amount').focus(), 200);
}

function closeAddModal() {
  document.getElementById('modal-backdrop').hidden = true;
}

function setEntryType(type) {
  currentEntryType = type;
  selectedCategoryId = null;
  document.getElementById('type-expense').classList.toggle('active', type === 'expense');
  document.getElementById('type-income').classList.toggle('active', type === 'income');
  renderCategoryGrid();
}

function renderAccountGrid() {
  const grid = document.getElementById('account-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.accounts.forEach(acc => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedAccountId === acc.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${acc.icon}</span><span>${escapeHtml(acc.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedAccountId = acc.id;
      renderAccountGrid();
    });
    grid.appendChild(chip);
  });
}

function renderCategoryGrid() {
  const grid = document.getElementById('category-grid');
  const list = currentEntryType === 'income' ? state.incomeCategories : state.categories;
  grid.innerHTML = '';
  list.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryId === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryId = cat.id;
      renderCategoryGrid();
    });
    grid.appendChild(chip);
  });
}

function saveEntry() {
  const amountRaw = document.getElementById('input-amount').value;
  const amount = parseFloat(amountRaw);
  const note = document.getElementById('input-note').value.trim();
  const date = document.getElementById('input-date').value || todayISO();

  if (!amount || amount <= 0) {
    showToast('Ingresá un monto válido');
    return;
  }
  if (!selectedCategoryId) {
    showToast('Elegí una categoría');
    return;
  }
  if (!selectedAccountId) {
    showToast('Elegí una cuenta');
    return;
  }

  state.entries.push({
    id: uid(),
    type: currentEntryType,
    amount: amount,
    categoryId: selectedCategoryId,
    accountId: selectedAccountId,
    note: note,
    date: date,
    createdAt: Date.now(),
  });

  saveState();
  closeAddModal();
  renderAll();
  showToast(currentEntryType === 'expense' ? 'Gasto anotado' : 'Ingreso anotado');
}

/* ============================================
   VIEW: STATS
   ============================================ */

function renderStats() {
  const now = new Date();
  document.getElementById('stats-month-label').textContent = monthLabel(now);

  const thisMonthEntries = getEntriesForMonth(now);
  const expense = thisMonthEntries.filter(e => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
  const income = thisMonthEntries.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0);

  // average daily spend (based on days elapsed in month)
  const daysElapsed = now.getDate();
  const avgDaily = daysElapsed > 0 ? expense / daysElapsed : 0;
  document.getElementById('metric-avg-daily').textContent = formatMoney(avgDaily);

  // savings rate
  const savingsRate = income > 0 ? ((income - expense) / income) * 100 : 0;
  const rateEl = document.getElementById('metric-savings-rate');
  rateEl.textContent = `${Math.round(savingsRate)}%`;
  rateEl.classList.toggle('positive', savingsRate >= 0);
  rateEl.classList.toggle('negative', savingsRate < 0);

  // vs last month
  const lastMonthDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const lastMonthEntries = getEntriesForMonth(lastMonthDate);
  const lastExpense = lastMonthEntries.filter(e => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
  const vsEl = document.getElementById('metric-vs-last');
  if (lastExpense > 0) {
    const diff = ((expense - lastExpense) / lastExpense) * 100;
    vsEl.textContent = `${diff >= 0 ? '+' : ''}${Math.round(diff)}%`;
    vsEl.classList.toggle('negative', diff > 0);
    vsEl.classList.toggle('positive', diff <= 0);
  } else {
    vsEl.textContent = '—';
    vsEl.classList.remove('positive', 'negative');
  }

  // days logged this month
  const distinctDays = new Set(thisMonthEntries.map(e => e.date)).size;
  const daysInMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate();
  document.getElementById('metric-days-logged').textContent = `${distinctDays}/${daysInMonth}`;

  renderCategoryBars(thisMonthEntries, expense);
  renderTrendChart();
}

function renderCategoryBars(monthEntries, totalExpense) {
  const container = document.getElementById('category-bars');
  container.innerHTML = '';

  if (totalExpense === 0) {
    container.innerHTML = '<p style="font-size:13px;color:var(--ink-faint);text-align:center;padding:20px 0;">todavía no hay gastos este mes</p>';
    return;
  }

  const totals = {};
  monthEntries.filter(e => e.type === 'expense').forEach(e => {
    totals[e.categoryId] = (totals[e.categoryId] || 0) + e.amount;
  });

  const sorted = Object.entries(totals).sort((a, b) => b[1] - a[1]);

  sorted.forEach(([catId, amount]) => {
    const cat = getCategoryById(catId, 'expense');
    const budget = state.budgets ? state.budgets.find(b => b.categoryId === catId) : null;

    let barWidth, barFillClass, amountLabel, overflowLabel = '';

    if (budget) {
      const budgetPct = (amount / budget.monthlyLimit) * 100;
      barWidth = Math.min(100, budgetPct);
      amountLabel = `${formatMoney(amount)} / ${formatMoney(budget.monthlyLimit)} · ${Math.round(budgetPct)}%`;
      barFillClass = budgetPct >= 100 ? 'over-budget' : budgetPct >= 80 ? 'near-budget' : '';
      if (budgetPct > 100) {
        overflowLabel = `<span class="budget-overflow">+${Math.round(budgetPct - 100)}% sobre límite</span>`;
      }
    } else {
      const pct = (amount / totalExpense) * 100;
      barWidth = pct;
      amountLabel = `${formatMoney(amount)} · ${Math.round(pct)}%`;
      barFillClass = '';
    }

    const row = document.createElement('div');
    row.className = 'category-bar-row';
    row.innerHTML = `
      <div class="category-bar-top">
        <span class="category-bar-name"><span>${cat.icon}</span>${escapeHtml(cat.name)}</span>
        <span class="category-bar-amount">${amountLabel}</span>
      </div>
      <div class="category-bar-track"><div class="category-bar-fill ${barFillClass}" style="width:${barWidth}%"></div></div>
      ${overflowLabel}
    `;
    container.appendChild(row);
  });
}

function renderTrendChart() {
  const container = document.getElementById('trend-chart');
  container.innerHTML = '';

  const months = [];
  for (let i = 5; i >= 0; i--) {
    const d = new Date();
    d.setDate(1);
    d.setMonth(d.getMonth() - i);
    months.push(d);
  }

  const monthTotals = months.map(d => {
    const entries = getEntriesForMonth(d);
    const income = entries.filter(e => e.type === 'income').reduce((s, e) => s + e.amount, 0);
    const expense = entries.filter(e => e.type === 'expense').reduce((s, e) => s + e.amount, 0);
    return { date: d, income, expense };
  });

  const maxVal = Math.max(1, ...monthTotals.map(m => Math.max(m.income, m.expense)));

  monthTotals.forEach(m => {
    const col = document.createElement('div');
    col.className = 'trend-month';

    const incomeH = Math.max(2, (m.income / maxVal) * 100);
    const expenseH = Math.max(2, (m.expense / maxVal) * 100);

    col.innerHTML = `
      <div class="trend-bars">
        <div class="trend-bar income" style="height:${incomeH}%"></div>
        <div class="trend-bar expense" style="height:${expenseH}%"></div>
      </div>
      <span class="trend-month-label">${MONTH_NAMES[m.date.getMonth()].slice(0,3)}</span>
    `;
    container.appendChild(col);
  });
}

/* ============================================
   VIEW: GOALS
   ============================================ */

function renderGoals() {
  const body = document.getElementById('goals-body');
  body.innerHTML = '';

  if (state.goals.length === 0) {
    body.innerHTML = `
      <div class="empty-goals">
        <p>todavía no tenés metas de ahorro</p>
        <p style="font-size:13px;">tocá + arriba para crear la primera</p>
      </div>`;
    return;
  }

  state.goals.forEach(goal => {
    const pct = Math.min(100, Math.round((goal.current / goal.target) * 100));
    const card = document.createElement('div');
    card.className = 'goal-card';
    card.innerHTML = `
      <div class="goal-top">
        <p class="goal-name">${escapeHtml(goal.name)}</p>
        <span class="goal-pct">${pct}%</span>
      </div>
      <div class="goal-track"><div class="goal-fill" style="width:${pct}%"></div></div>
      <div class="goal-amounts">
        <span><strong>${formatMoney(goal.current)}</strong> ahorrado</span>
        <span>meta: <strong>${formatMoney(goal.target)}</strong></span>
      </div>
      <div class="goal-add-funds">
        <input type="number" inputmode="decimal" placeholder="sumar monto" id="add-fund-${goal.id}">
        <button data-goal-id="${goal.id}" class="btn-add-fund">sumar</button>
      </div>
    `;
    body.appendChild(card);
  });

  body.querySelectorAll('.btn-add-fund').forEach(btn => {
    btn.addEventListener('click', () => {
      const goalId = btn.dataset.goalId;
      const input = document.getElementById(`add-fund-${goalId}`);
      const val = parseFloat(input.value);
      if (!val || val <= 0) { showToast('Ingresá un monto válido'); return; }
      const goal = state.goals.find(g => g.id === goalId);
      goal.current += val;
      saveState();
      renderGoals();
      showToast('Ahorro actualizado');
    });
  });
}

function openGoalModal() {
  closeAllModals();
  document.getElementById('goal-name').value = '';
  document.getElementById('goal-target').value = '';
  document.getElementById('goal-current').value = '';
  document.getElementById('goal-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeGoalModal() {
  document.getElementById('goal-modal-backdrop').hidden = true;
}

function saveGoal() {
  const name = document.getElementById('goal-name').value.trim();
  const target = parseFloat(document.getElementById('goal-target').value);
  const current = parseFloat(document.getElementById('goal-current').value) || 0;

  if (!name) { showToast('Ponele un nombre a la meta'); return; }
  if (!target || target <= 0) { showToast('Ingresá un monto objetivo válido'); return; }

  state.goals.push({ id: uid(), name, target, current });
  saveState();
  closeGoalModal();
  renderGoals();
  showToast('Meta creada');
}

/* ============================================
   VIEW: SETTINGS
   ============================================ */

function renderCategoryManager() {
  const container = document.getElementById('category-manager');
  container.innerHTML = '';
  state.categories.forEach(cat => {
    const row = document.createElement('div');
    row.className = 'category-manager-row';
    row.innerHTML = `
      <span><span>${cat.icon}</span>${escapeHtml(cat.name)}</span>
      <button class="cat-remove" data-cat-id="${cat.id}">quitar</button>
    `;
    container.appendChild(row);
  });
  container.querySelectorAll('.cat-remove').forEach(btn => {
    btn.addEventListener('click', () => {
      const id = btn.dataset.catId;
      const inUse = state.entries.some(e => e.categoryId === id);
      if (inUse) {
        showToast('No se puede quitar: tiene movimientos cargados');
        return;
      }
      state.categories = state.categories.filter(c => c.id !== id);
      saveState();
      renderCategoryManager();
    });
  });
}

function openCategoryModal() {
  closeAllModals();
  document.getElementById('new-cat-name').value = '';
  selectedIconForNewCategory = ICON_OPTIONS[0];
  renderIconPicker();
  document.getElementById('cat-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeCategoryModal() {
  document.getElementById('cat-modal-backdrop').hidden = true;
}

function renderIconPicker() {
  const picker = document.getElementById('icon-picker');
  picker.innerHTML = '';
  ICON_OPTIONS.forEach(icon => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'icon-picker-item' + (selectedIconForNewCategory === icon ? ' selected' : '');
    btn.textContent = icon;
    btn.addEventListener('click', () => {
      selectedIconForNewCategory = icon;
      renderIconPicker();
    });
    picker.appendChild(btn);
  });
}

function saveCategory() {
  const name = document.getElementById('new-cat-name').value.trim();
  if (!name) { showToast('Ponele un nombre'); return; }
  state.categories.push({ id: uid(), name, icon: selectedIconForNewCategory });
  saveState();
  closeCategoryModal();
  renderCategoryManager();
  showToast('Categoría agregada');
}

/* ============================================
   VIEW: ACCOUNTS (within Settings)
   ============================================ */

function renderAccountManager() {
  const container = document.getElementById('account-manager');
  if (!container) return;
  container.innerHTML = '';
  state.accounts.forEach(acc => {
    const row = document.createElement('div');
    row.className = 'category-manager-row';
    row.innerHTML = `
      <span><span>${acc.icon}</span>${escapeHtml(acc.name)}</span>
      <button class="cat-remove" data-acc-id="${acc.id}">quitar</button>
    `;
    container.appendChild(row);
  });
  container.querySelectorAll('.cat-remove').forEach(btn => {
    btn.addEventListener('click', () => {
      const id = btn.dataset.accId;
      const inUse = state.entries.some(e => e.accountId === id);
      if (inUse) { showToast('No se puede quitar: tiene movimientos cargados'); return; }
      state.accounts = state.accounts.filter(a => a.id !== id);
      saveState();
      renderAccountManager();
    });
  });
}

function openAccountModal() {
  closeAllModals();
  document.getElementById('new-account-name').value = '';
  selectedIconForNewAccount = ACCOUNT_ICON_OPTIONS[0];
  selectedAccountType = 'cash';
  renderAccountIconPicker();
  updateAccountTypeSelector();
  document.getElementById('account-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeAccountModal() {
  document.getElementById('account-modal-backdrop').hidden = true;
}

function renderAccountIconPicker() {
  const picker = document.getElementById('account-icon-picker');
  if (!picker) return;
  picker.innerHTML = '';
  ACCOUNT_ICON_OPTIONS.forEach(icon => {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'icon-picker-item' + (selectedIconForNewAccount === icon ? ' selected' : '');
    btn.textContent = icon;
    btn.addEventListener('click', () => {
      selectedIconForNewAccount = icon;
      renderAccountIconPicker();
    });
    picker.appendChild(btn);
  });
}

function updateAccountTypeSelector() {
  document.querySelectorAll('#account-type-selector .account-type-btn').forEach(btn => {
    btn.classList.toggle('selected', btn.dataset.type === selectedAccountType);
  });
}

function saveAccount() {
  const name = document.getElementById('new-account-name').value.trim();
  if (!name) { showToast('Ponele un nombre a la cuenta'); return; }
  state.accounts.push({ id: uid(), name, icon: selectedIconForNewAccount, type: selectedAccountType });
  saveState();
  closeAccountModal();
  renderAccountManager();
  showToast('Cuenta agregada');
}

/* ============================================
   VIEW: BUDGETS (within Settings)
   ============================================ */

function renderBudgetManager() {
  const container = document.getElementById('budget-manager');
  if (!container) return;
  container.innerHTML = '';

  if (!state.budgets || state.budgets.length === 0) {
    container.innerHTML = '<p class="recurring-empty">todavía no hay presupuestos definidos</p>';
    return;
  }

  state.budgets.forEach(budget => {
    const cat = getCategoryById(budget.categoryId, 'expense');
    const row = document.createElement('div');
    row.className = 'category-manager-row';
    row.innerHTML = `
      <span><span>${cat.icon}</span>${escapeHtml(cat.name)}<span class="budget-limit-tag">${formatMoney(budget.monthlyLimit)}/mes</span></span>
      <button class="cat-remove" data-budget-cat="${budget.categoryId}">quitar</button>
    `;
    container.appendChild(row);
  });

  container.querySelectorAll('.cat-remove[data-budget-cat]').forEach(btn => {
    btn.addEventListener('click', () => {
      state.budgets = state.budgets.filter(b => b.categoryId !== btn.dataset.budgetCat);
      saveState();
      renderBudgetManager();
    });
  });
}

function openBudgetModal() {
  closeAllModals();
  document.getElementById('budget-limit').value = '';
  selectedCategoryIdForBudget = null;
  renderBudgetCategorySelector();
  document.getElementById('budget-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeBudgetModal() {
  document.getElementById('budget-modal-backdrop').hidden = true;
}

function renderBudgetCategorySelector() {
  const grid = document.getElementById('budget-category-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.categories.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryIdForBudget === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryIdForBudget = cat.id;
      renderBudgetCategorySelector();
      // Pre-fill existing limit if any
      const existing = state.budgets.find(b => b.categoryId === cat.id);
      document.getElementById('budget-limit').value = existing ? existing.monthlyLimit : '';
    });
    grid.appendChild(chip);
  });
}

function saveBudget() {
  const limit = parseFloat(document.getElementById('budget-limit').value);
  if (!selectedCategoryIdForBudget) { showToast('Elegí una categoría'); return; }
  if (!limit || limit <= 0) { showToast('Ingresá un límite válido'); return; }

  const existing = state.budgets.findIndex(b => b.categoryId === selectedCategoryIdForBudget);
  if (existing >= 0) {
    state.budgets[existing].monthlyLimit = limit;
  } else {
    state.budgets.push({ categoryId: selectedCategoryIdForBudget, monthlyLimit: limit });
  }

  saveState();
  closeBudgetModal();
  renderBudgetManager();
  showToast('Presupuesto guardado');
}

/* ============================================
   VIEW: RECURRING EXPENSES (within Settings)
   ============================================ */

function renderRecurringManager() {
  const container = document.getElementById('recurring-manager');
  if (!container) return;
  container.innerHTML = '';

  if (state.recurringExpenses.length === 0) {
    container.innerHTML = '<p class="recurring-empty">todavía no hay gastos fijos</p>';
    return;
  }

  state.recurringExpenses.forEach(rec => {
    const cat = getCategoryById(rec.categoryId, 'expense');
    const row = document.createElement('div');
    row.className = 'recurring-row';
    row.innerHTML = `
      <div class="recurring-row-info">
        <span class="recurring-row-name">${cat.icon} ${escapeHtml(rec.name)}</span>
        <span class="recurring-row-detail">${formatMoney(rec.amount)} · día ${rec.dayOfMonth}</span>
      </div>
      <div class="recurring-row-actions">
        <button class="recurring-toggle${rec.active ? ' active' : ''}" data-rec-id="${rec.id}">
          ${rec.active ? 'pausar' : 'activar'}
        </button>
        <button class="cat-remove" data-rec-id="${rec.id}">quitar</button>
      </div>
    `;
    container.appendChild(row);
  });

  container.querySelectorAll('.recurring-toggle').forEach(btn => {
    btn.addEventListener('click', () => {
      const rec = state.recurringExpenses.find(r => r.id === btn.dataset.recId);
      if (!rec) return;
      rec.active = !rec.active;
      saveState();
      renderRecurringManager();
    });
  });

  container.querySelectorAll('.cat-remove[data-rec-id]').forEach(btn => {
    btn.addEventListener('click', () => {
      state.recurringExpenses = state.recurringExpenses.filter(r => r.id !== btn.dataset.recId);
      saveState();
      renderRecurringManager();
    });
  });
}

function openRecurringModal() {
  closeAllModals();
  document.getElementById('recurring-name').value = '';
  document.getElementById('recurring-amount').value = '';
  document.getElementById('recurring-day').value = '';
  selectedCategoryIdForRecurring = null;
  selectedAccountIdForRecurring = state.accounts.length > 0 ? state.accounts[0].id : null;
  renderRecurringCategoryGrid();
  renderRecurringAccountGrid();
  document.getElementById('recurring-modal-backdrop').hidden = false;
  history.pushState({ overlay: true }, '');
}

function closeRecurringModal() {
  document.getElementById('recurring-modal-backdrop').hidden = true;
}

function renderRecurringCategoryGrid() {
  const grid = document.getElementById('recurring-category-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.categories.forEach(cat => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedCategoryIdForRecurring === cat.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${cat.icon}</span><span>${escapeHtml(cat.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedCategoryIdForRecurring = cat.id;
      renderRecurringCategoryGrid();
    });
    grid.appendChild(chip);
  });
}

function renderRecurringAccountGrid() {
  const grid = document.getElementById('recurring-account-grid');
  if (!grid) return;
  grid.innerHTML = '';
  state.accounts.forEach(acc => {
    const chip = document.createElement('button');
    chip.type = 'button';
    chip.className = 'category-chip' + (selectedAccountIdForRecurring === acc.id ? ' selected' : '');
    chip.innerHTML = `<span class="chip-icon">${acc.icon}</span><span>${escapeHtml(acc.name)}</span>`;
    chip.addEventListener('click', () => {
      selectedAccountIdForRecurring = acc.id;
      renderRecurringAccountGrid();
    });
    grid.appendChild(chip);
  });
}

function saveRecurring() {
  const name = document.getElementById('recurring-name').value.trim();
  const amount = parseFloat(document.getElementById('recurring-amount').value);
  const day = parseInt(document.getElementById('recurring-day').value, 10);

  if (!name) { showToast('Ponele un nombre al gasto fijo'); return; }
  if (!amount || amount <= 0) { showToast('Ingresá un monto válido'); return; }
  if (!day || day < 1 || day > 28) { showToast('El día debe estar entre 1 y 28'); return; }
  if (!selectedCategoryIdForRecurring) { showToast('Elegí una categoría'); return; }
  if (!selectedAccountIdForRecurring) { showToast('Elegí una cuenta'); return; }

  state.recurringExpenses.push({
    id: uid(),
    name,
    amount,
    categoryId: selectedCategoryIdForRecurring,
    accountId: selectedAccountIdForRecurring,
    dayOfMonth: day,
    active: true,
  });

  saveState();
  closeRecurringModal();
  renderRecurringManager();
  showToast('Gasto fijo agregado');
}

function exportData() {
  const dataStr = JSON.stringify(state, null, 2);
  const blob = new Blob([dataStr], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `libro-de-caja-${todayISO()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  showToast('Datos exportados');
}

function clearAllData() {
  if (!confirm('¿Seguro que querés borrar TODOS los datos? Esta acción no se puede deshacer.')) return;
  if (!confirm('Última confirmación: se van a borrar todos los movimientos, metas y categorías personalizadas.')) return;
  state = {
    entries: [],
    categories: DEFAULT_CATEGORIES,
    incomeCategories: DEFAULT_INCOME_CATEGORIES,
    goals: [],
    accounts: [...DEFAULT_ACCOUNTS],
    recurringExpenses: [],
    budgets: [],
    streak: { count: 0, lastDate: null },
  };
  saveState();
  renderAll();
  renderCategoryManager();
  renderBudgetManager();
  renderAccountManager();
  renderRecurringManager();
  showToast('Todos los datos fueron borrados');
}

/* ============================================
   VIEW NAVIGATION
   ============================================ */

function showView(viewName) {
  closeAllModals();
  document.getElementById('view-stats').hidden = viewName !== 'stats';
  document.getElementById('view-goals').hidden = viewName !== 'goals';
  document.getElementById('view-settings').hidden = viewName !== 'settings';

  document.querySelectorAll('.nav-item').forEach(item => {
    item.classList.toggle('active', item.dataset.view === viewName);
  });

  if (viewName === 'stats') renderStats();
  if (viewName === 'goals') renderGoals();
  if (viewName === 'settings') { renderCategoryManager(); renderBudgetManager(); renderAccountManager(); renderRecurringManager(); }
  history.pushState({ overlay: true }, '');
}

function hideAllOverlays() {
  closeAllOverlaysAndModals();
}

/* ============================================
   EVENT LISTENERS
   ============================================ */

function attachEventListeners() {
  // FAB + modal
  document.getElementById('btn-add').addEventListener('click', openAddModal);
  document.getElementById('btn-cancel-entry').addEventListener('click', closeAddModal);
  document.getElementById('modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'modal-backdrop') closeAddModal();
  });
  document.getElementById('btn-save-entry').addEventListener('click', saveEntry);
  document.getElementById('type-expense').addEventListener('click', () => setEntryType('expense'));
  document.getElementById('type-income').addEventListener('click', () => setEntryType('income'));

  // Month navigation
  document.getElementById('prev-month').addEventListener('click', () => {
    viewDate.setMonth(viewDate.getMonth() - 1);
    renderAll();
  });
  document.getElementById('next-month').addEventListener('click', () => {
    viewDate.setMonth(viewDate.getMonth() + 1);
    renderAll();
  });

  // Filter pills
  document.getElementById('filter-pills').addEventListener('click', (e) => {
    const pill = e.target.closest('.pill');
    if (!pill) return;
    currentFilter = pill.dataset.filter;
    document.querySelectorAll('.pill').forEach(p => p.classList.toggle('active', p === pill));
    renderLedger();
  });

  // Bottom nav
  document.querySelectorAll('.nav-item').forEach(item => {
    item.addEventListener('click', () => {
      const view = item.dataset.view;
      if (view === 'ledger') { hideAllOverlays(); return; }
      showView(view);
    });
  });
  document.getElementById('btn-open-stats').addEventListener('click', () => showView('stats'));

  // Back buttons
  document.getElementById('stats-back').addEventListener('click', hideAllOverlays);
  document.getElementById('goals-back').addEventListener('click', hideAllOverlays);
  document.getElementById('settings-back').addEventListener('click', hideAllOverlays);

  // Goals
  document.getElementById('btn-add-goal').addEventListener('click', openGoalModal);
  document.getElementById('btn-cancel-goal').addEventListener('click', closeGoalModal);
  document.getElementById('goal-modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'goal-modal-backdrop') closeGoalModal();
  });
  document.getElementById('btn-save-goal').addEventListener('click', saveGoal);

  // Settings: categories
  document.getElementById('btn-add-category').addEventListener('click', openCategoryModal);
  document.getElementById('btn-cancel-category').addEventListener('click', closeCategoryModal);
  document.getElementById('cat-modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'cat-modal-backdrop') closeCategoryModal();
  });
  document.getElementById('btn-save-category').addEventListener('click', saveCategory);

  // Settings: budgets
  document.getElementById('btn-add-budget').addEventListener('click', openBudgetModal);
  document.getElementById('btn-cancel-budget').addEventListener('click', closeBudgetModal);
  document.getElementById('budget-modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'budget-modal-backdrop') closeBudgetModal();
  });
  document.getElementById('btn-save-budget').addEventListener('click', saveBudget);

  // Settings: recurring expenses
  document.getElementById('btn-add-recurring').addEventListener('click', openRecurringModal);
  document.getElementById('btn-cancel-recurring').addEventListener('click', closeRecurringModal);
  document.getElementById('recurring-modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'recurring-modal-backdrop') closeRecurringModal();
  });
  document.getElementById('btn-save-recurring').addEventListener('click', saveRecurring);

  // Settings: accounts
  document.getElementById('btn-add-account').addEventListener('click', openAccountModal);
  document.getElementById('btn-cancel-account').addEventListener('click', closeAccountModal);
  document.getElementById('account-modal-backdrop').addEventListener('click', (e) => {
    if (e.target.id === 'account-modal-backdrop') closeAccountModal();
  });
  document.getElementById('btn-save-account').addEventListener('click', saveAccount);
  document.querySelectorAll('#account-type-selector .account-type-btn').forEach(btn => {
    btn.addEventListener('click', () => {
      selectedAccountType = btn.dataset.type;
      updateAccountTypeSelector();
    });
  });

  // Settings: data
  document.getElementById('btn-export').addEventListener('click', exportData);
  document.getElementById('btn-clear-data').addEventListener('click', clearAllData);

  // Android / browser back button: close topmost overlay instead of exiting
  window.addEventListener('popstate', () => {
    closeTopmostOverlay();
    if (getTopmostOverlay()) {
      history.pushState({ overlay: true }, '');
    }
  });
}

/* ============================================
   INIT
   ============================================ */

function init() {
  loadState();
  attachEventListeners();
  renderAll();
  processRecurringExpenses();
}

document.addEventListener('DOMContentLoaded', init);
